
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml

http:
  cors_allowed_origins:
    - http://hub.fritz.box
  use_x_forwarded_for: true
  trusted_proxies:
    # Trust all proxies
    - 0.0.0.0/0
