- id: '1719660110957'
  name: 'Living Room: Bright'
  entities:
    light.tz3210_cieijuw1_ts0505b_light:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Center Light
      supported_features: 40
      state: 'on'
    light.living_room_dining_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Dining Light
      supported_features: 40
      state: 'on'
    light.living_room_corner_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Corner Light
      supported_features: 40
      state: 'on'
    light.living_room_window_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Window Light
      supported_features: 40
      state: 'on'
  icon: mdi:white-balance-sunny
  metadata: {}
- id: '1719660589970'
  name: 'Living Room: Sunset'
  entities:
    light.tz3210_cieijuw1_ts0505b_light:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 254
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 308.125
      - 37.647
      rgb_color:
      - 255
      - 159
      - 242
      xy_color:
      - 0.371
      - 0.239
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Center Light
      supported_features: 40
      state: 'on'
    light.living_room_dining_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 254
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 308.125
      - 37.647
      rgb_color:
      - 255
      - 159
      - 242
      xy_color:
      - 0.371
      - 0.239
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Dining Light
      supported_features: 40
      state: 'on'
    light.living_room_corner_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 254
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 9.231
      - 66.275
      rgb_color:
      - 255
      - 112
      - 86
      xy_color:
      - 0.589
      - 0.329
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Corner Light
      supported_features: 40
      state: 'on'
    light.living_room_window_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 254
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 9.231
      - 66.275
      rgb_color:
      - 255
      - 112
      - 86
      xy_color:
      - 0.589
      - 0.329
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Window Light
      supported_features: 40
      state: 'on'
  icon: mdi:weather-sunset
  metadata: {}
