- id: '1719660110957'
  name: 'Living Room: Bright'
  entities:
    light.tz3210_cieijuw1_ts0505b_light:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Center Light
      supported_features: 40
      state: 'on'
    light.living_room_dining_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Dining Light
      supported_features: 40
      state: 'on'
    light.living_room_corner_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Corner Light
      supported_features: 40
      state: 'on'
    light.living_room_window_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Window Light
      supported_features: 40
      state: 'on'
  icon: mdi:white-balance-sunny
  metadata: {}
