- id: '1719516774300'
  name: 'Living Room Lights: Bright'
  entities:
    light.living_room_center_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 224
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Center Light
      supported_features: 40
      state: 'on'
    light.living_room_corner_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 247
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Corner Light
      supported_features: 40
      state: 'on'
    light.living_room_table_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 242
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Table Light
      supported_features: 40
      state: 'on'
    light.living_room_window_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 230
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Window Light
      supported_features: 40
      state: 'on'
  metadata: {}
- id: '1719516833435'
  name: 'Living Room Lights: Cozy'
  entities:
    light.living_room_center_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 97
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Center Light
      supported_features: 40
      state: 'on'
    light.living_room_corner_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 97
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Corner Light
      supported_features: 40
      state: 'on'
    light.living_room_table_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 97
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Table Light
      supported_features: 40
      state: 'on'
    light.living_room_window_light:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 97
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Living Room Window Light
      supported_features: 40
      state: 'on'
  metadata: {}
